# To build quarto book locally...

# Move to the Build tab and press Render Book (figuring out difference between preview annd render)
# Or you could run the "quarto preview" command in terminal
# (optionally add a file name such as index.qmd to the end of the command to render a specific file)

# This will render the entire website locally in quarto.

# If there are no errors in the files then this should locally preview the entire primer
# Take a look around to make sure that you're changes are working (even if there are no errors)

# We used the _quarto.yml file from https://github.com/jjallaire/hopr. 

# Tried to use pre-render field for Quarto instead of the before_chapter_script field, 
# which was previously used in bookdown. Alas, there seens to be no eqivalent of 
# before_chapter_script and after_chapter_script in Quarto. Each chapter must be self-contained.
# For more info see: https://community.rstudio.com/t/cannot-get-quarto-pre-render-to-work/143566

project:
  type: book
  output-dir: docs

book:
  title: "Preceptor's Primer for Bayesian Data Science: Using the Cardinal Virtues for Inference"
  author: "David Kane"
  biblio-style: apalike
  link-citations: yes
  nocite: '@*'
  colorlinks: yes
  lot: false
  lof: false
  always_allow_html: yes
  graphics: yes
  search: true
  repo-url: https://github.com/PPBDS/primer/
  repo-actions: [edit]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - preamble.qmd
    - 00-getting-started.qmd
    - 01-visualization.qmd
    - 02-wrangling.qmd
    - 03-data.qmd
    - 04-rubin-causal-model.qmd
    - 05-probability.qmd
    - 06-one-parameter.qmd
    - 07-two-parameters.qmd
    - 08-three-parameters.qmd
    - 09-four-parameters.qmd
    - 10-five-parameters.qmd
    - 11-n-parameters.qmd
    - style_guide.qmd
    - set-up.qmd
    - references.qmd

# Added downloads as pdf and epub. Not working?
# Bib files used to kept in a bib subdirectory but I got a render error.
# For now I took them out of the directory and it is working

bibliography:
  - references.bib
  - packages.bib


# Trying to add option to download as a pdf/epub doc but this causes an 
# error so we commented it out.

format:
  html:
    theme: cosmo
    code-link: true
  # pdf:
  #   documentclass: krantz
  #   keep-tex: true
  #   cite-method: natbib
